### ISSUE TITLE
paprica_numght devient PAPRICA_NUMGHT => incompatible avec pmeasyr

### ISSUE THREAD

**Issue by AlexandreGGS** [GuillaumePressiat/nomensland#13]
Bonjour Guillaume,

La fonction get_table('tarifs_had_ght') ramène un tibble pour lequel le nom de la première colonne est désormais en majuscules (précédemment en minuscules).
![image](https://github.com/GuillaumePressiat/nomensland/assets/25608769/fcab81cb-3192-4369-9004-0bc3ee628513)

Le problème est que cela n'est plus compatible avec la fonction pmeasyr::vvr_had_ght()
Pourrais-tu corriger ?

Merci

**Comment by GuillaumePressiat** [comment]
Bonjour Alexandre,

Arf désolé. Je me doutais bien en le faisant.
Je vais regarder
