### ISSUE TITLE
Mise à jour tarifs HAD

### ISSUE THREAD

**Issue by AlexandreGGS** [GuillaumePressiat/nomensland#2]
Salut Guillaume,

Pourrais-tu mettre à jour la table : tarifs_had_ght.json.gz avec les tarifs 2020 ?

Je ne sais pas trop quelle méthode tu utilises pour faire tes mises à jour à partir des fichiers de l'ATIH...

Merci pour ton aide,

A bientôt,

Alexandre

**Comment by GuillaumePressiat** [comment]
Bonjour Alexandre, 

C'est fait désormais.

Pour la méthode et son partage, on peut l'envisager sur gitlab dans un groupe plus restreint peut-être ? 
Sur ce fichier pas trop d'intelligence donc pas de pb pour partager la méthode (jo en pdf > Tabula pour extraire le tableau en csv que j'ajoute au csv contenant toutes les années, je ne passe pas par le fichier de l'ATIH qui ne contient que les tarifs GHT standard, je préfère prendre les valeurs avec arrondi à deux décimales du jo pour être sûr d'être ok pour les ESMS et SSIAD également). C'est le même principe pour le fichier oqn.csv si tu en as besoin, dis-moi.

Sur d'autres sujets nomenclature, je vais probablement garder le pli d'un partage du résultat et pas de la méthode intégrale. 
On peut voir de plus en plus que les projets open source sont comme de la confiture (ou du miel*) pour certains.

Bonne continuation et dispo si besoin.

Guillaume

---
 *[*Bees make honey, who needs money ? Monopoly*](https://www.youtube.com/watch?v=PP5XRxFgRlY)
