### ISSUE TITLE
table cim_hierarchie_codes non référencée

### ISSUE THREAD

**Issue by AlexandreGGS** [GuillaumePressiat/nomensland#3]
Bonjour Guillaume,
Comme indiqué dans le titre, quand tu utilises la fonction explore_nomensland()
la table cim_hierarchie_codes n'apparaît pas, je suppose qu'il faut mettre à jour la table de référencement / le dictionnaire.

Merci pour ce précieux package.

A+

Alexandre

**Comment by GuillaumePressiat** [comment]
Bonjour Alexandre,

C'est corrigé, merci. Ce petit souci vient probablement de la "migration" depuis la base de l'api referime AP-HP vers le sqlite (pas encore mis proprement en Posgres ou autre, manque de temps) sur mon poste perso, je n'avais visiblement pas mis à jour le dico en cohérence. Je l'ai fait vite fait ici pour répondre à ce besoin d'apparence de cim_hierarchie_code dans explore_nomensland/shiny.


Pour d'autres qui liraient ceci, voir ici pour un aperçu http://guillaumepressiat.shinyapps.io/nomensweb

A+
Guillaume
